# Based on https://blog.codeship.com/running-rails-development-environment-docker/
version: "1.0"
services:
  app:
    build: .
    environment:
      - DATABASE_HOST=mysql
    command: /app/script/server
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  mysql:
    image: mariadb:10.11.2 # Matches features of mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306"