# This is a basic workflow to help you get started with Actions

name: Github actions for DBC Freehub testing
env:
  RUBY_VER: "3.2"

# Controls when the action will run.
on:
  # Triggers the workflow on a push/pull to the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run_tests"
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Set up Ruby ${{env.RUBY_VER}} and dependencies"
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${RUBY_VER}
            bundler-cache: true
